workflows:
  ios-workflow:
    name: CoreArsitek iOS Build
    max_build_duration: 60
    environment:
      node: 20.11.1
      xcode: 15.2
      cocoapods: default
    scripts:
      - name: Install Node dependencies
        script: |
          npm install

      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update || pod install
          cd ..

      - name: Ensure Info.plist values
        script: |
          PLIST="ios/CoreArsitek/Info.plist"
          /usr/libexec/PlistBuddy -c "Set :CFBundleDisplayName CoreArsitek" $PLIST || true
          /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier com.corearsitek.app" $PLIST || true
          /usr/libexec/PlistBuddy -c "Add :NSAppTransportSecurity:NSAllowsArbitraryLoads bool true" $PLIST || true

      - name: Build iOS IPA
        script: |
          if [ -d "ios/CoreArsitek.xcworkspace" ]; then
            xcode-project build-ipa \
              --workspace ios/CoreArsitek.xcworkspace \
              --scheme CoreArsitek
          else
            xcode-project build-ipa \
              --project ios/CoreArsitek.xcodeproj \
              --scheme CoreArsitek
          fi

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - your@email.com
